# Generated by Django 4.2.5 on 2024-04-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price_per_day', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('auto_confirm', models.BooleanField(default=True)),
                ('with_furniture', models.BooleanField(default=True)),
                ('property_ownership', models.CharField(blank=True, max_length=200, null=True)),
                ('area_size', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
